#include "IO/PoscarSerializer.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>

namespace ds
{

    namespace
    {

        int ClampPrecision(int precision)
        {
            if (precision < 1)
            {
                return 1;
            }
            if (precision > 16)
            {
                return 16;
            }
            return precision;
        }

        std::string FormatScalarFixed(double value, int width, int precision)
        {
            std::ostringstream out;
            out << std::fixed << std::setw(width) << std::setprecision(precision) << value;
            return out.str();
        }

        std::string FormatVec3Fixed(const glm::vec3 &v, int width, int precision)
        {
            std::ostringstream out;
            out << std::fixed << std::setprecision(precision)
                << std::setw(width) << v.x
                << std::setw(width) << v.y
                << std::setw(width) << v.z;
            return out.str();
        }

        bool BuildSpeciesOrder(const Structure &structure, std::vector<std::string> &outSpecies, std::vector<int> &outCounts)
        {
            if (!structure.species.empty() && structure.species.size() == structure.counts.size())
            {
                outSpecies = structure.species;
                outCounts = structure.counts;
                return true;
            }

            Structure rebuilt = structure;
            rebuilt.RebuildSpeciesFromAtoms();
            outSpecies = rebuilt.species;
            outCounts = rebuilt.counts;
            return !outSpecies.empty() || rebuilt.atoms.empty();
        }

    } // namespace

    bool PoscarSerializer::WriteToFile(const Structure &structure, const std::string &path, const PoscarWriteOptions &options, std::string &error) const
    {
        std::string text;
        if (!WriteToString(structure, options, text, error))
        {
            return false;
        }

        const std::filesystem::path outputPath(path);
        const std::filesystem::path parent = outputPath.parent_path();
        if (!parent.empty())
        {
            std::error_code ec;
            std::filesystem::create_directories(parent, ec);
            if (ec)
            {
                error = "Failed to create output directory: " + parent.string();
                return false;
            }
        }

        std::ofstream out(path, std::ios::trunc);
        if (!out.is_open())
        {
            error = "Failed to open output file: " + path;
            return false;
        }

        out << text;
        if (!out.good())
        {
            error = "Failed to write output file: " + path;
            return false;
        }

        return true;
    }

    bool PoscarSerializer::WriteToString(const Structure &structure, const PoscarWriteOptions &options, std::string &outText, std::string &error) const
    {
        Structure writable = structure;

        std::string conversionError;
        if (!writable.ConvertAtomsTo(options.coordinateMode, conversionError))
        {
            error = conversionError;
            return false;
        }

        std::vector<std::string> species;
        std::vector<int> counts;
        if (!BuildSpeciesOrder(writable, species, counts))
        {
            error = "Failed to build species list for export.";
            return false;
        }

        const bool hasSelectiveDynamics = options.forceSelectiveDynamics || writable.HasSelectiveDynamics();
        const int coordinatePrecision = std::max(16, ClampPrecision(options.precision));
        constexpr int kScalePrecision = 14;
        constexpr int kLatticeWidth = 23;
        constexpr int kCoordinateWidth = 20;

        std::ostringstream stream;

        const std::string title = writable.title.empty() ? "Generated by DefectsStudio" : writable.title;
        stream << title << '\n';
        stream << FormatScalarFixed(1.0, 19, kScalePrecision) << '\n';

        for (int i = 0; i < 3; ++i)
        {
            stream << FormatVec3Fixed(writable.lattice[i], kLatticeWidth, coordinatePrecision) << '\n';
        }

        if (!species.empty())
        {
            stream << "   ";
            for (std::size_t i = 0; i < species.size(); ++i)
            {
                if (i > 0)
                {
                    stream << ' ';
                }
                stream << species[i];
            }
            stream << '\n';

            stream << "   ";
            for (std::size_t i = 0; i < counts.size(); ++i)
            {
                if (i > 0)
                {
                    stream << ' ';
                }
                stream << counts[i];
            }
            stream << '\n';
        }
        else
        {
            stream << "X\n";
            stream << "0\n";
        }

        if (hasSelectiveDynamics)
        {
            stream << "Selective Dynamics\n";
        }

        stream << (options.coordinateMode == CoordinateMode::Direct ? "Direct\n" : "Cartesian\n");

        std::vector<std::size_t> writtenIndices;
        writtenIndices.reserve(writable.atoms.size());

        for (const std::string &speciesName : species)
        {
            for (std::size_t atomIndex = 0; atomIndex < writable.atoms.size(); ++atomIndex)
            {
                const Atom &atom = writable.atoms[atomIndex];
                if (atom.element != speciesName)
                {
                    continue;
                }

                writtenIndices.push_back(atomIndex);
                stream << FormatVec3Fixed(atom.position, kCoordinateWidth, coordinatePrecision);

                if (hasSelectiveDynamics)
                {
                    const bool sx = atom.selectiveDynamics ? atom.selectiveFlags[0] : true;
                    const bool sy = atom.selectiveDynamics ? atom.selectiveFlags[1] : true;
                    const bool sz = atom.selectiveDynamics ? atom.selectiveFlags[2] : true;
                    stream << ' ' << (sx ? 'T' : 'F') << ' ' << (sy ? 'T' : 'F') << ' ' << (sz ? 'T' : 'F');
                }

                stream << '\n';
            }
        }

        if (writtenIndices.size() != writable.atoms.size())
        {
            error = "Species list does not cover all atoms; cannot export.";
            return false;
        }

        outText = stream.str();
        return true;
    }

} // namespace ds
